In [16]:
import numpy
import numpy as np

a = numpy.zeros((3,3))
b = numpy.matrix('1 2 3; 4 5 6; 7 8 9; 6 7 8')
c = numpy.matrix('1; 2; 3')

print a
print b
print c
print b.shape
print c.shape
print np.where(b==3)
print np.where(b==6)


[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [6 7 8]]
[[1]
 [2]
 [3]]
(4, 3)
(3, 1)
(array([0]), array([2]))
(array([1, 3]), array([2, 0]))


In [32]:
X = numpy.matrix('1 2 3; 3 2 1')
print X
Y = numpy.matrix('5 6 7; 1 2 4')
print Y
print len(X)

for i in range(len(X)):
    for j in range(len(Y)):
        result = (X[i] + Y[j])
        print result

[[1 2 3]
 [3 2 1]]
[[5 6 7]
 [1 2 4]]
2
[[ 6  8 10]]
[[2 4 7]]
[[8 8 8]]
[[4 4 5]]
